package Helena::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Helena::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=helena;host=localhost',
        user => 'helena',
        password => 'helena',
        loader_options => {components => ["TimeStamp","PassphraseColumn"],generate_pod => 0,moniker_map => {processes_defendants => "ProcessDefendant",processes_keepers => "ProcessKeeper",processes_plaintiffs => "ProcessPlaintiff",users_roles => "UserRole"}},
        pg_enable_utf8 => q{1},
        quote_char => q{"},
    }
);

=head1 NAME

Helena::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Helena>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Helena::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

sgrs

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
