use utf8;
{
    model_config => {
        resultset => 'Person',
    },
    auto_container_class => 'form-group',
    elements => [
        { type => 'Hidden',
          name => 'id' },
        { type => 'Text',
          name => 'name',
          label => 'Nome',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'mother',
          label => 'Nome da Mãe',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'father',
          label => 'Nome do Pai',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'cnpjf',
          label => 'CPF / CNPJ',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'rg',
          label => 'RG',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'email',
          label => 'Email',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'phone',
          label => 'Telefone',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'phone2',
          label => 'Telefone 2',
          attrs => { class => 'form-control' } },
        { type => 'Text',
          name => 'phone3',
          label => 'Telefone 3',
          attrs => { class => 'form-control' } },
        { type => 'Textarea',
          name => 'address',
          label => 'Endereço',
          attrs => { class => 'form-control', rows => 5 } },
        { type => 'Textarea',
          name => 'address2',
          label => 'Endereço 2',
          attrs => { class => 'form-control', rows => 5 } },
        { type => 'Textarea',
          name => 'comment',
          label => 'Comentário',
          attrs => { class => 'form-control', rows => 2 } },
        { type => 'Submit',
          value => 'Enviar',
          attrs => { class => 'btn btn-primary' } },
    ],
}
